### ISSUE TITLE
https://github.com/agustingenoud/infovis/blob/gh-pages/zoo.txt

### ISSUE THREAD

**Issue by aaizemberg** [agustingenoud/infovis#1]
Debería estar en plain-text y me parece que estas intentando generar .md (markdown)

**Comment by agustingenoud** [comment]
> Debería estar en plain-text y me parece que estas intentando generar .md (markdown)

Lo hice con vim, con el editor de txt de mac lo pude abrir bien, linux también. Me fijo bien a ver que puede ser.

**Comment by agustingenoud** [comment]
Creo que ya entendí, capaz pensaste que era .md por los # y los *, pero en realidad solo los estaba usando a modo de "bullets", para diferenciar título, notas y tabs con ' ' para las citas del texto.
